// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewProject(arg1, arg2) {
  return window['go']['main']['App']['CreateNewProject'](arg1, arg2);
}

export function CreateNewTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateNewTask'](arg1, arg2, arg3);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function EditTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EditTask'](arg1, arg2, arg3, arg4);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadFromDB() {
  return window['go']['main']['App']['LoadFromDB']();
}

export function UpdateTaskState(arg1, arg2) {
  return window['go']['main']['App']['UpdateTaskState'](arg1, arg2);
}
