// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewProject(arg1:string,arg2:string):Promise<void>;

export function CreateNewTask(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteTask(arg1:string):Promise<void>;

export function EditProject(arg1:string,arg2:string):Promise<void>;

export function EditTask(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function LoadFromDB():Promise<string>;

export function UpdateTaskState(arg1:string,arg2:string):Promise<void>;
